### ISSUE TITLE
make hexxed.io live and renew subscription

### ISSUE THREAD

**Issue by synapticleft** [quendera/TheSpinnerGame#66]
Ask Margarida to pay for another year of hexxed.io through bial grant - let @synapticleft know if he can help.

**Comment by quendera** [comment]
@synapticleft , we should refuel the funds for server costs. How much do you think we can use from the BIAL?
Tiago

**Comment by synapticleft** [comment]
Specifically this is for the cost of the domain name? what cap would you recommend?

**Comment by quendera** [comment]
hey g, thanks for the follow up email.
It says it expires in 2 days and I'm getting anxious. How should I proceed?

**Comment by synapticleft** [comment]
My understanding from Guida is that you have all you need now?

**Comment by quendera** [comment]
done!
