### ISSUE TITLE
icon looks heavily aliased on android 10

### ISSUE THREAD

**Issue by synapticleft** [quendera/TheSpinnerGame#75]
After upgrading to android 10 icon started looking weird, as if many invisible lines suddenly popped up -- is it in SVG?

**Comment by quendera** [comment]
could you post a printscreen here?

**Comment by synapticleft** [comment]
![image](https://user-images.githubusercontent.com/1248211/86841281-98b6e700-c058-11ea-802c-ed59315a5172.png)
