### ISSUE TITLE
Graphics (aesthetics)

### ISSUE THREAD

**Issue by quendera** [quendera/TheSpinnerGame#9]
- [x] Basic grid
- Glow grid
- [x] Red

- Animations: 
- [x] Grid
- [x] Slider
- [x] Collect

**Comment by quendera** [comment]
https://www.youtube.com/watch?v=AX-6h6E4r-0

cool game

**Comment by quendera** [comment]
fix angles,
gap between lower and upper

**Comment by quendera** [comment]
Graphics connecting to the score bar.

**Comment by synapticleft** [comment]
good to go
