### ISSUE TITLE
reset users included in leaderboard on server end

### ISSUE THREAD

**Issue by synapticleft** [quendera/TheSpinnerGame#91]
remove all players with '0' score in total player count

**Comment by quendera** [comment]
done!

**Comment by quendera** [comment]
how I did it:

I moved all the data to a different table named "gd_pre_v2".
I then filtered our regular table (now backed up) and filtered for entries with score > 0.
voila.

**Comment by synapticleft** [comment]
thanks. What is gd vs gd_old vs gd_pre_v2?
